In [1]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [6]:
x = np.array([45,67,87,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 87 60]
<class 'numpy.ndarray'>
int32


In [7]:
x = np.array([45,67,87,9.9])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  87.   9.9]
<class 'numpy.ndarray'>
float64


In [8]:
x = np.array(['A',67,87,9.9])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '87' '9.9']
<class 'numpy.ndarray'>
<U32


In [9]:
a = np.array([[23,45],[90,89]])
print(a)
print(type(a))
print(a.shape)

[[23 45]
 [90 89]]
<class 'numpy.ndarray'>
(2, 2)


In [10]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [12]:
c = np.arange(3,5)
print(c)
type(c)

[3 4]


numpy.ndarray

In [14]:
d = np.array([1.34, 3.16650, 4.9999])
print(d)
np.around(d,2)

[1.34   3.1665 4.9999]


array([1.34, 3.17, 5.  ])

In [15]:
d = np.array([1.3456, 5.9987,4.9876])
print(d)
print(np.around(np.sqrt(d),2))

[1.3456 5.9987 4.9876]
[1.16 2.45 2.23]


In [16]:
a = np.array([[4,5,6,7],[7,3,4,np.NaN]])
print(a)
a.dtype

[[ 4.  5.  6.  7.]
 [ 7.  3.  4. nan]]


dtype('float64')

In [17]:
a = np.array([[4,5,6,7],[7,3,4,np.NaN]])
a_copy = a.astype(str)
print(a_copy)
a_copy.dtype

[['4.0' '5.0' '6.0' '7.0']
 ['7.0' '3.0' '4.0' 'nan']]


dtype('<U32')

In [18]:
a = np.array([[3,4,5],[5,6,7],[7,8,9]])
a

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [19]:
a.sum(axis=1)

array([12, 18, 24])

In [20]:
a.sum(axis=0)

array([15, 18, 21])

In [22]:
a.mean(axis=0)

array([5., 6., 7.])

In [23]:
a.mean(axis=1)

array([4., 6., 8.])

In [24]:
a = np.array([[3,4,5],[5,6,7],[7,8,9]])
a

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [25]:
a = np.array([[3,4,5],[5,6,7],[7,8,9]])
a
np.fill_diagonal(a,0)
a

array([[0, 4, 5],
       [5, 0, 7],
       [7, 8, 0]])

In [ ]:
a = np.array([[3,4,5],[5,6,7]]
b = np.array([[3,9,5],[7,6,7]]            

In [26]:
print(a.T)
print(b.T)

[[0 5 7]
 [4 0 8]
 [5 7 0]]
[[10 30]
 [20 40]]


In [27]:
a = np.array([[3,4,5],[5,6,7],[7,8,9],[10,9,8]])
a

array([[ 3,  4,  5],
       [ 5,  6,  7],
       [ 7,  8,  9],
       [10,  9,  8]])

In [28]:
a[2][2]

9

In [29]:
a[0][2]

5

In [30]:
a[1:3,0:2]

array([[5, 6],
       [7, 8]])

In [31]:
a = np.array([[3,4,5],[5,6,7],[7,8,9]])
a

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [32]:
print(np.argmax(a,axis=1))
print(np.argmax(a,axis=0))

[2 2 2]
[2 2 2]
