In [1]:
import pandas as pd

In [4]:
#create pandas series using list
data = [10, 20, 30]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
dtype: int64


In [6]:
data = [1,2,3,4]
i = ['A', 'B','C','D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [7]:
data = {'a': 10,'b': 55,'c': 66}
series = pd.Series(data)
print(data)

{'a': 10, 'b': 55, 'c': 66}


In [8]:
series.replace(55,100)

a     10
b    100
c     66
dtype: int64

In [11]:
import pandas as np
data = np.array([100,200,300])
series = pd.Series(data,index=['a','b','c'])
print(series)



a    100
b    200
c    300
dtype: Int64


In [12]:
import pandas as pd
data = {'Name':['Bablu','Likhi','Varsha'], 'Age':[18,19,17], 'Country':["India","Uk","Usa"]}
df = pd.DataFrame(data)
df

Name  Age Country
0   Bablu   18   India
1   Likhi   19      Uk
2  Varsha   17     Usa

In [14]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
df

[[1 2 3]
 [4 5 6]
 [7 8 9]]


A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
data = [[1,'Likhi',19],[2,'Bablu',17],[3,'Varsha',18]]
print(data)
df = pd.DataFrame(array, columns=['Id', 'Name', 'Age'])
df
                  
                        

[[1, 'Likhi', 19], [2, 'Bablu', 17], [3, 'Varsha', 18]]


Id  Name  Age
0   1     2    3
1   4     5    6
2   7     8    9

In [17]:
iris_df = pd.read_csv("Iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [21]:
iris_df = pd.read_excel("iris.xlsx")
print(iris_df)

FileNotFoundError: [Errno 2] No such file or directory: 'iris.xlsx'